export { default as Box } from './box'
export { default as Img } from './img'
export { default as Text } from './text'
export { default as Heading } from './heading'
export { default as Flex } from './flex'
export { default as Figure } from './figure'
export { default as Figcaption } from './figcaption'
export * from './faIcons'