export { default as Box } from './Box';
export { default as Img } from './Img';
export { default as Text } from './Text';
export { default as Heading } from './Heading';
export { default as Flex } from './Flex';
export { default as Figure } from './Figure';
export { default as Figcaption } from './Figcaption';
export { default as VStack } from './VStack';
export { default as SocialIcon } from './SocialIcon';
